### ISSUE TITLE
Leerzeichen vor Tilde notwendig

### ISSUE THREAD

**Issue by AndreasHDrescher** [CRegenschein/maldix-aiml-cs-tools#1]
Werden im Konverter Klammern gesetzt, wie in 
montezuma\* " [~role_nationality_member_male_d
sieht alles prima aus, ist das aber nicht der Fall,
so hängen Anführungszeichen und Tilde aufeinander,
obwohl ChatScript zum Verständnis einen Leerschritt 
dazwischen braucht, also anstatt No1 die No 2:
No1: montezuma\* "~role_nationality_member_male_d
No2: montezuma\* " ~role_nationality_member_male_d

**Comment by dannybusch** [comment]
fixed in 1.0.3
