### ISSUE TITLE
Anführungszeichen in Concepts sollten enthaltene Wörter zu einem verschmelzen

### ISSUE THREAD

**Issue by AndreasHDrescher** [CRegenschein/maldix-aiml-cs-tools#3]
Der Konverter matcht zuweilen 
Einzelwörter in Anführungsstrichen, die,
ebenso wie die Underscores, mehrere 
Wörter zu_einem_Ganzen, oder "zu einem Ganzen"
zusammenfassen sollten, also in den Beispielen
keine Matchings bei nur "zu", nur "einem" oder nur "Ganzen".

Hier ein Beispiel für den beschriebenen Fall:

Match ~mathematician_ with Weil in Deschhalb verschtehe isch disch so schlescht! Weil du Aachener Printen knabberscht!

Teilansicht des betreffenden Concepts:

concept: ~mathematician_20_century_male_d (
    "Alan Turing"
    "Alexander Grothendieck"
    "André Weil"
...

**Comment by dannybusch** [comment]
Ich denke, hier ist das Problem das Unicode Zeichen é gewesen (siehe Issue #4), dadurch wurde André Weil gesplittet in Andr und Weil.

**Comment by dannybusch** [comment]
Falls es sonst keine Beispiele mehr dafür gibt, dass die Phrasen nicht richtig gematched werden, bitte das Issue schließen.
